window.esdocSearchIndex = [
  [
    "@jobandtalent/nevada/strip-types/src/dom/core.js~$",
    "variable/index.html#static-variable-$",
    "<span>$</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/dom/core.js</span>",
    "variable"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/component/base/base-controller.js~basecontroller",
    "class/strip-types/src/component/base/base-controller.js~BaseController.html",
    "<span>BaseController</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/component/base/base-controller.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/component/base/base-view.js~baseview",
    "class/strip-types/src/component/base/base-view.js~BaseView.html",
    "<span>BaseView</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/component/base/base-view.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/clone-object.js~cloneobject",
    "class/strip-types/src/clone-object.js~CloneObject.html",
    "<span>CloneObject</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/clone-object.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/cookie-storage.js~cookiestorage",
    "class/strip-types/src/cookie-storage.js~CookieStorage.html",
    "<span>CookieStorage</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/cookie-storage.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/dom-mutation/mutation-base.js~dommutationbase",
    "class/strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase.html",
    "<span>DOMMutationBase</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/dom-mutation/mutation-base.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/dom-mutation/mutation-events.js~dommutationevents",
    "class/strip-types/src/test-framework/dom-mutation/mutation-events.js~DOMMutationEvents.html",
    "<span>DOMMutationEvents</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/dom-mutation/mutation-events.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/dom-mutation/factory.js~dommutationfactory",
    "class/strip-types/src/test-framework/dom-mutation/factory.js~DOMMutationFactory.html",
    "<span>DOMMutationFactory</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/dom-mutation/factory.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/dom-mutation/mutation-observer.js~dommutationobserver",
    "class/strip-types/src/test-framework/dom-mutation/mutation-observer.js~DOMMutationObserver.html",
    "<span>DOMMutationObserver</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/dom-mutation/mutation-observer.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/dom-util.js~domutil",
    "class/strip-types/src/test-framework/dom-util.js~DOMUtil.html",
    "<span>DOMUtil</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/dom-util.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/component/base/event.js~documentevents",
    "variable/index.html#static-variable-DocumentEvents",
    "<span>DocumentEvents</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/component/base/event.js</span>",
    "variable"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/erb-templating.js~erbtemplating",
    "variable/index.html#static-variable-ERBTemplating",
    "<span>ERBTemplating</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/erb-templating.js</span>",
    "variable"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/component/base/event.js~elementevents",
    "variable/index.html#static-variable-ElementEvents",
    "<span>ElementEvents</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/component/base/event.js</span>",
    "variable"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/environment.js~environment",
    "class/strip-types/src/environment.js~Environment.html",
    "<span>Environment</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/environment.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/component/base/event-actions.js~eventactions",
    "class/strip-types/src/component/base/event-actions.js~EventActions.html",
    "<span>EventActions</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/component/base/event-actions.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/inject.js~inject",
    "class/strip-types/src/test-framework/inject.js~Inject.html",
    "<span>Inject</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/inject.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/mock.js~mock",
    "class/strip-types/src/test-framework/mock.js~Mock.html",
    "<span>Mock</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/mock.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/modulejs.js~modulejs",
    "class/strip-types/src/test-framework/modulejs.js~ModuleJS.html",
    "<span>ModuleJS</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/modulejs.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/module-naming.js~modulenaming",
    "class/strip-types/src/module-naming.js~ModuleNaming.html",
    "<span>ModuleNaming</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/module-naming.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/proxy-spy-handler.js~proxyspyhandler",
    "class/strip-types/src/test-framework/proxy-spy-handler.js~ProxySpyHandler.html",
    "<span>ProxySpyHandler</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/proxy-spy-handler.js</span>",
    "class"
  ],
  [
    "@jobandtalent/nevada/strip-types/src/test-framework/spy.js~spy",
    "class/strip-types/src/test-framework/spy.js~Spy.html",
    "<span>Spy</span> <span class=\"search-result-import-path\">@jobandtalent/nevada/strip-types/src/test-framework/spy.js</span>",
    "class"
  ],
  [
    "basecontroller strip-types/src/component/base/base-controller.js~basecontroller,basecontroller",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber14",
    "BaseController",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber41",
    "BaseController A state id is generated",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber106",
    "BaseController State changes are propagated",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber53",
    "BaseController With a document window a store is initialized",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber69",
    "BaseController doesn't render a view on initialize",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber84",
    "BaseController generates properly a view name based on controller's class name",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber90",
    "BaseController has a view",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber76",
    "BaseController renders a view on demand",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber62",
    "BaseController renders a view on initialization",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-controller.js.html#lineNumber96",
    "BaseController renders emits a renderBaseController event",
    "test"
  ],
  [
    "baseview strip-types/src/component/base/base-view.js~baseview,baseview",
    "test-file/test/javascript/component/base/test.base-view.js.html#lineNumber14",
    "BaseView",
    "test"
  ],
  [
    "baseview#loadtemplate baseview#loadtemplate,baseview#loadtemplate",
    "test-file/test/javascript/component/base/test.base-view.js.html#lineNumber91",
    "BaseView Autoloads the template in the development environment",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-view.js.html#lineNumber69",
    "BaseView Gets augmented via EventActions",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.base-view.js.html#lineNumber83",
    "BaseView has a $ property",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "cloneobject strip-types/src/clone-object.js~cloneobject,cloneobject",
    "test-file/test/javascript/test.clone-object.js.html#lineNumber9",
    "CloneObject",
    "test"
  ],
  [
    "cloneobject#clone strip-types/src/clone-object.js~cloneobject#clone,cloneobject#clone",
    "test-file/test/javascript/test.clone-object.js.html#lineNumber20",
    "CloneObject Can clone objects",
    "test"
  ],
  [
    "cloneobject#clonewithout strip-types/src/clone-object.js~cloneobject#clonewithout,cloneobject#clonewithout",
    "test-file/test/javascript/test.clone-object.js.html#lineNumber36",
    "CloneObject Can clone objects properties conditionally",
    "test"
  ],
  [
    "cookiestorage strip-types/src/cookie-storage.js~cookiestorage,cookiestorage",
    "test-file/test/javascript/test.cookie-storage.js.html#lineNumber10",
    "CookieStorage",
    "test"
  ],
  [
    "cookiestorage#set strip-types/src/cookie-storage.js~cookiestorage#set,cookiestorage#set",
    "test-file/test/javascript/test.cookie-storage.js.html#lineNumber21",
    "CookieStorage Cookie values are set",
    "test"
  ],
  [
    "cookiestorage#removeall strip-types/src/cookie-storage.js~cookiestorage#removeall,cookiestorage#removeall",
    "test-file/test/javascript/test.cookie-storage.js.html#lineNumber49",
    "CookieStorage Cookies can be removed globally",
    "test"
  ],
  [
    "cookiestorage#remove strip-types/src/cookie-storage.js~cookiestorage#remove,cookiestorage#remove",
    "test-file/test/javascript/test.cookie-storage.js.html#lineNumber37",
    "CookieStorage Cookies can be removed individually",
    "test"
  ],
  [
    "erbtemplating strip-types/src/erb-templating.js~erbtemplating,erbtemplating",
    "test-file/test/javascript/test.erb-templating.js.html#lineNumber9",
    "ERBTemplating",
    "test"
  ],
  [
    "erbtemplating#filter erbtemplating#filter,erbtemplating#filter",
    "test-file/test/javascript/test.erb-templating.js.html#lineNumber13",
    "ERBTemplating Filter individual strings",
    "test"
  ],
  [
    "erbtemplating#filter erbtemplating#filter,erbtemplating#filter",
    "test-file/test/javascript/test.erb-templating.js.html#lineNumber26",
    "ERBTemplating Filter templates with multiple matches",
    "test"
  ],
  [
    "erbtemplating#_replacematches erbtemplating#_replacematches,erbtemplating#_replacematches",
    "test-file/test/javascript/test.erb-templating.js.html#lineNumber44",
    "ERBTemplating Replacing placeholders with matches",
    "test"
  ],
  [
    "environment strip-types/src/environment.js~environment,environment",
    "test-file/test/javascript/test.environment.js.html#lineNumber9",
    "Environment",
    "test"
  ],
  [
    "environment#isdevelopment strip-types/src/environment.js~environment#isdevelopment,environment#isdevelopment",
    "test-file/test/javascript/test.environment.js.html#lineNumber13",
    "Environment Environment is set to production by default",
    "test"
  ],
  [
    "environment#set environment#set,environment#set",
    "test-file/test/javascript/test.environment.js.html#lineNumber21",
    "Environment The environment information can be set",
    "test"
  ],
  [
    "eventactions strip-types/src/component/base/event-actions.js~eventactions,eventactions",
    "test-file/test/javascript/component/base/test.event-actions.js.html#lineNumber13",
    "EventActions",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.event-actions.js.html#lineNumber70",
    "EventActions Augments views based on generic events",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.event-actions.js.html#lineNumber66",
    "EventActions Augments views based on locators",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.event-actions.js.html#lineNumber75",
    "EventActions Clears event handlers",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.event-actions.js.html#lineNumber93",
    "EventActions Event handlers receive the event object",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.event-actions.js.html#lineNumber109",
    "EventActions Object locators receive the event object",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.event-actions.js.html#lineNumber59",
    "EventActions Returns proper event action names",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/component/base/test.event-actions.js.html#lineNumber129",
    "EventActions Translates locator object/strings",
    "test"
  ],
  [
    "eventbus eventbus,eventbus",
    "test-file/test/javascript/test.event-bus.js.html#lineNumber7",
    "EventBus",
    "test"
  ],
  [
    "eventbus#subscribe eventbus#publish eventbus#subscribe,eventbus#subscribe eventbus#publish,eventbus#publish",
    "test-file/test/javascript/test.event-bus.js.html#lineNumber16",
    "EventBus #subscribe listeners can subscribe to events",
    "test"
  ],
  [
    "eventbus#subscribe eventbus#publish eventbus#subscribe,eventbus#subscribe eventbus#publish,eventbus#publish",
    "test-file/test/javascript/test.event-bus.js.html#lineNumber30",
    "EventBus #subscribe listeners receive events data",
    "test"
  ],
  [
    "logger logger,logger",
    "test-file/test/javascript/test.logger.js.html#lineNumber8",
    "Logger",
    "test"
  ],
  [
    "logger#debug logger#info logger#warn logger#error logger#debug,logger#debug logger#info,logger#info logger#warn,logger#warn logger#error,logger#error",
    "test-file/test/javascript/test.logger.js.html#lineNumber39",
    "Logger #debug #info #warn #error trigger console calls",
    "test"
  ],
  [
    "mock strip-types/src/test-framework/mock.js~mock,mock",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber10",
    "Mock",
    "test"
  ],
  [
    "mock strip-types/src/test-framework/mock.js~mock,mock",
    "test-file/test/javascript/test-framework/test.mock.js.html#lineNumber9",
    "Mock",
    "test"
  ],
  [
    "mock#attach strip-types/src/test-framework/mock.js~mock#attach,mock#attach",
    "test-file/test/javascript/test-framework/test.mock.js.html#lineNumber39",
    "Mock #attach should inject a mock in the global scope",
    "test"
  ],
  [
    "mock#destroy strip-types/src/test-framework/mock.js~mock#destroy,mock#destroy",
    "test-file/test/javascript/test-framework/test.mock.js.html#lineNumber49",
    "Mock #destroy should remove a mock from the global scope",
    "test"
  ],
  [
    "mock#get mock#get,mock#get",
    "test-file/test/javascript/test-framework/test.mock.js.html#lineNumber60",
    "Mock #get returns the mocked object",
    "test"
  ],
  [
    "mock#set mock#set,mock#set",
    "test-file/test/javascript/test-framework/test.mock.js.html#lineNumber67",
    "Mock #set sets the mocked object",
    "test"
  ],
  [
    "domobserver#observe domobserver#getmutationdata domobserver#observe,domobserver#observe domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber198",
    "Mock domMutation#getMutationData DOM mutation adding a node.",
    "test"
  ],
  [
    "domobserver#observe domobserver#getmutationdata domobserver#observe,domobserver#observe domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber166",
    "Mock domMutation#getMutationData DOM mutation in existing attribute is detected.",
    "test"
  ],
  [
    "domobserver#observe domobserver#getmutationdata domobserver#observe,domobserver#observe domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber182",
    "Mock domMutation#getMutationData DOM mutation in new attribute is detected.",
    "test"
  ],
  [
    "domobserver#observe domobserver#getmutationdata domobserver#observe,domobserver#observe domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber213",
    "Mock domMutation#getMutationData DOM mutation removing a node.",
    "test"
  ],
  [
    "domobserver#getmutationdata domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber140",
    "Mock domMutation#getMutationData DOM mutation without observe returns undefined for attributes.",
    "test"
  ],
  [
    "domobserver#observe domobserver#getmutationdata domobserver#observe,domobserver#observe domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber112",
    "Mock domMutation#getMutationData with no mutation returns undefined for every attribute.",
    "test"
  ],
  [
    "domobserver#getmutationdata domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber122",
    "Mock domMutation#getMutationData with no observe and no mutation returns undefined attributes.",
    "test"
  ],
  [
    "domobserver#getmutationdata domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber131",
    "Mock domMutation#getMutationData with no observe returns undefined for every attribute.",
    "test"
  ],
  [
    "domobserver#observe domobserver#getmutationdata domobserver#observe,domobserver#observe domobserver#getmutationdata,domobserver#getmutationdata",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber152",
    "Mock domMutation#isActive tracks properly if a DOM element is being observed",
    "test"
  ],
  [
    "domobserver#observe domobserver#observer domobserver#observe,domobserver#observe domobserver#observer,domobserver#observer",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html#lineNumber100",
    "Mock domMutation#observe throws error if trying to observe invalid element.",
    "test"
  ],
  [
    "modulejs strip-types/src/test-framework/modulejs.js~modulejs,modulejs",
    "test-file/test/javascript/test-framework/test.modulejs.js.html#lineNumber8",
    "ModuleJS",
    "test"
  ],
  [
    "modulejs#attach strip-types/src/test-framework/mock.js~mock#attach,modulejs#attach",
    "test-file/test/javascript/test-framework/test.modulejs.js.html#lineNumber40",
    "ModuleJS #attach intercepts modulejs calls",
    "test"
  ],
  [
    "modulejs#getmodule strip-types/src/test-framework/modulejs.js~modulejs#getmodule,modulejs#getmodule",
    "test-file/test/javascript/test-framework/test.modulejs.js.html#lineNumber49",
    "ModuleJS #getModule returns the Module constructor",
    "test"
  ],
  [
    "polyfill polyfill,polyfill",
    "test-file/test/javascript/polyfill/test.polyfill.js.html#lineNumber9",
    "Polyfill",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/polyfill/test.polyfill.js.html#lineNumber20",
    "Polyfill addEventListener",
    "test"
  ],
  [
    "",
    "test-file/test/javascript/polyfill/test.polyfill.js.html#lineNumber13",
    "Polyfill customEvent",
    "test"
  ],
  [
    "spy strip-types/src/test-framework/spy.js~spy,spy",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber10",
    "Spy",
    "test"
  ],
  [
    "spy#restore strip-types/src/test-framework/spy.js~spy#restore,spy#restore",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber208",
    "Spy #instance.method.restore",
    "test"
  ],
  [
    "spy#intercept strip-types/src/test-framework/spy.js~spy#intercept,spy#intercept",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber184",
    "Spy #intercept can receive stubs",
    "test"
  ],
  [
    "spy#intercept strip-types/src/test-framework/spy.js~spy#intercept,spy#intercept",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber169",
    "Spy #intercept counts method calls",
    "test"
  ],
  [
    "spy#intercept strip-types/src/test-framework/spy.js~spy#intercept,spy#intercept",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber149",
    "Spy #intercept overrides method calls",
    "test"
  ],
  [
    "spy#intercept strip-types/src/test-framework/spy.js~spy#intercept,spy#intercept",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber159",
    "Spy #intercept registers method calls",
    "test"
  ],
  [
    "spy#mock strip-types/src/test-framework/spy.js~spy#mock,spy#mock",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber217",
    "Spy #mock can override modulejs modules",
    "test"
  ],
  [
    "spy#mock strip-types/src/test-framework/spy.js~spy#mock,spy#mock",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber245",
    "Spy #mock can restore modulejs modules",
    "test"
  ],
  [
    "spy#get strip-types/src/test-framework/spy.js~spy#get,spy#get",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber92",
    "Spy #spy counts properly multiple property sets",
    "test"
  ],
  [
    "spy#get strip-types/src/test-framework/spy.js~spy#get,spy#get",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber84",
    "Spy #spy intercepts invalid property sets",
    "test"
  ],
  [
    "spy#get strip-types/src/test-framework/spy.js~spy#get,spy#get",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber120",
    "Spy #spy intercepts invalid property sets",
    "test"
  ],
  [
    "spy#get strip-types/src/test-framework/spy.js~spy#get,spy#get",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber128",
    "Spy #spy intercepts method calls",
    "test"
  ],
  [
    "spy#get strip-types/src/test-framework/spy.js~spy#get,spy#get",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber138",
    "Spy #spy intercepts multiple method calls",
    "test"
  ],
  [
    "spy#get strip-types/src/test-framework/spy.js~spy#get,spy#get",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber111",
    "Spy #spy intercepts multiple property sets",
    "test"
  ],
  [
    "spy#get strip-types/src/test-framework/spy.js~spy#get,spy#get",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber103",
    "Spy #spy intercepts property gets",
    "test"
  ],
  [
    "spy#get strip-types/src/test-framework/spy.js~spy#get,spy#get",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber74",
    "Spy #spy intercepts property sets",
    "test"
  ],
  [
    "spy#watch strip-types/src/test-framework/spy.js~spy#watch,spy#watch",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber67",
    "Spy #spy spied proxy preserves original values",
    "test"
  ],
  [
    "spy#watched strip-types/src/test-framework/spy.js~spy#watched,spy#watched",
    "test-file/test/javascript/test-framework/test.spy.js.html#lineNumber198",
    "Spy #watched",
    "test"
  ],
  [
    "eventbus eventbus,eventbus",
    "test-file/test/javascript/test.emit-core-ready-event.js.html#lineNumber6",
    "emit-core-ready-event",
    "test"
  ],
  [
    "eventbus#subscribe eventbus#publish eventbus#subscribe,eventbus#subscribe eventbus#publish,eventbus#publish",
    "test-file/test/javascript/test.emit-core-ready-event.js.html#lineNumber14",
    "emit-core-ready-event The event is emitted on file inclusion",
    "test"
  ],
  [
    "strip-types/src/clone-object.js",
    "file/strip-types/src/clone-object.js.html",
    "strip-types/src/clone-object.js",
    "file"
  ],
  [
    "strip-types/src/clone-object.js~cloneobject#clone",
    "class/strip-types/src/clone-object.js~CloneObject.html#instance-method-clone",
    "strip-types/src/clone-object.js~CloneObject#clone",
    "method"
  ],
  [
    "strip-types/src/clone-object.js~cloneobject#clonewithout",
    "class/strip-types/src/clone-object.js~CloneObject.html#instance-method-cloneWithout",
    "strip-types/src/clone-object.js~CloneObject#cloneWithout",
    "method"
  ],
  [
    "strip-types/src/component/base/base-controller.js",
    "file/strip-types/src/component/base/base-controller.js.html",
    "strip-types/src/component/base/base-controller.js",
    "file"
  ],
  [
    "strip-types/src/component/base/base-controller.js~basecontroller#constructor",
    "class/strip-types/src/component/base/base-controller.js~BaseController.html#instance-constructor-constructor",
    "strip-types/src/component/base/base-controller.js~BaseController#constructor",
    "method"
  ],
  [
    "strip-types/src/component/base/base-controller.js~basecontroller#getview",
    "class/strip-types/src/component/base/base-controller.js~BaseController.html#instance-method-getView",
    "strip-types/src/component/base/base-controller.js~BaseController#getView",
    "method"
  ],
  [
    "strip-types/src/component/base/base-controller.js~basecontroller#onstatechange",
    "class/strip-types/src/component/base/base-controller.js~BaseController.html#instance-method-onStateChange",
    "strip-types/src/component/base/base-controller.js~BaseController#onStateChange",
    "method"
  ],
  [
    "strip-types/src/component/base/base-controller.js~basecontroller#render",
    "class/strip-types/src/component/base/base-controller.js~BaseController.html#instance-method-render",
    "strip-types/src/component/base/base-controller.js~BaseController#render",
    "method"
  ],
  [
    "strip-types/src/component/base/base-view.js",
    "file/strip-types/src/component/base/base-view.js.html",
    "strip-types/src/component/base/base-view.js",
    "file"
  ],
  [
    "strip-types/src/component/base/base-view.js~baseview#constructor",
    "class/strip-types/src/component/base/base-view.js~BaseView.html#instance-constructor-constructor",
    "strip-types/src/component/base/base-view.js~BaseView#constructor",
    "method"
  ],
  [
    "strip-types/src/component/base/base-view.js~baseview#render",
    "class/strip-types/src/component/base/base-view.js~BaseView.html#instance-method-render",
    "strip-types/src/component/base/base-view.js~BaseView#render",
    "method"
  ],
  [
    "strip-types/src/component/base/event-actions.js",
    "file/strip-types/src/component/base/event-actions.js.html",
    "strip-types/src/component/base/event-actions.js",
    "file"
  ],
  [
    "strip-types/src/component/base/event-actions.js~eventactions#augment",
    "class/strip-types/src/component/base/event-actions.js~EventActions.html#instance-method-augment",
    "strip-types/src/component/base/event-actions.js~EventActions#augment",
    "method"
  ],
  [
    "strip-types/src/component/base/event-actions.js~eventactions#clear",
    "class/strip-types/src/component/base/event-actions.js~EventActions.html#instance-method-clear",
    "strip-types/src/component/base/event-actions.js~EventActions#clear",
    "method"
  ],
  [
    "strip-types/src/component/base/event-actions.js~eventactions#constructor",
    "class/strip-types/src/component/base/event-actions.js~EventActions.html#instance-constructor-constructor",
    "strip-types/src/component/base/event-actions.js~EventActions#constructor",
    "method"
  ],
  [
    "strip-types/src/component/base/event.js",
    "file/strip-types/src/component/base/event.js.html",
    "strip-types/src/component/base/event.js",
    "file"
  ],
  [
    "strip-types/src/cookie-storage.js",
    "file/strip-types/src/cookie-storage.js.html",
    "strip-types/src/cookie-storage.js",
    "file"
  ],
  [
    "strip-types/src/cookie-storage.js~cookiestorage#get",
    "class/strip-types/src/cookie-storage.js~CookieStorage.html#instance-method-get",
    "strip-types/src/cookie-storage.js~CookieStorage#get",
    "method"
  ],
  [
    "strip-types/src/cookie-storage.js~cookiestorage#remove",
    "class/strip-types/src/cookie-storage.js~CookieStorage.html#instance-method-remove",
    "strip-types/src/cookie-storage.js~CookieStorage#remove",
    "method"
  ],
  [
    "strip-types/src/cookie-storage.js~cookiestorage#removeall",
    "class/strip-types/src/cookie-storage.js~CookieStorage.html#instance-method-removeAll",
    "strip-types/src/cookie-storage.js~CookieStorage#removeAll",
    "method"
  ],
  [
    "strip-types/src/cookie-storage.js~cookiestorage#set",
    "class/strip-types/src/cookie-storage.js~CookieStorage.html#instance-method-set",
    "strip-types/src/cookie-storage.js~CookieStorage#set",
    "method"
  ],
  [
    "strip-types/src/dom/core.js",
    "file/strip-types/src/dom/core.js.html",
    "strip-types/src/dom/core.js",
    "file"
  ],
  [
    "strip-types/src/emit-core-ready-event.js",
    "file/strip-types/src/emit-core-ready-event.js.html",
    "strip-types/src/emit-core-ready-event.js",
    "file"
  ],
  [
    "strip-types/src/environment.js",
    "file/strip-types/src/environment.js.html",
    "strip-types/src/environment.js",
    "file"
  ],
  [
    "strip-types/src/environment.js~environment#development",
    "class/strip-types/src/environment.js~Environment.html#instance-member-DEVELOPMENT",
    "strip-types/src/environment.js~Environment#DEVELOPMENT",
    "member"
  ],
  [
    "strip-types/src/environment.js~environment#production",
    "class/strip-types/src/environment.js~Environment.html#instance-member-PRODUCTION",
    "strip-types/src/environment.js~Environment#PRODUCTION",
    "member"
  ],
  [
    "strip-types/src/environment.js~environment#isdevelopment",
    "class/strip-types/src/environment.js~Environment.html#instance-method-isDevelopment",
    "strip-types/src/environment.js~Environment#isDevelopment",
    "method"
  ],
  [
    "strip-types/src/erb-templating.js",
    "file/strip-types/src/erb-templating.js.html",
    "strip-types/src/erb-templating.js",
    "file"
  ],
  [
    "strip-types/src/module-naming.js",
    "file/strip-types/src/module-naming.js.html",
    "strip-types/src/module-naming.js",
    "file"
  ],
  [
    "strip-types/src/module-naming.js~modulenaming#underscoretocamelcase",
    "class/strip-types/src/module-naming.js~ModuleNaming.html#instance-method-underScoreToCamelCase",
    "strip-types/src/module-naming.js~ModuleNaming#underScoreToCamelCase",
    "method"
  ],
  [
    "strip-types/src/modulejs-core.js",
    "file/strip-types/src/modulejs-core.js.html",
    "strip-types/src/modulejs-core.js",
    "file"
  ],
  [
    "strip-types/src/polyfill/add-event-listener.js",
    "file/strip-types/src/polyfill/add-event-listener.js.html",
    "strip-types/src/polyfill/add-event-listener.js",
    "file"
  ],
  [
    "strip-types/src/polyfill/custom-event.js",
    "file/strip-types/src/polyfill/custom-event.js.html",
    "strip-types/src/polyfill/custom-event.js",
    "file"
  ],
  [
    "strip-types/src/reducer/base.js",
    "file/strip-types/src/reducer/base.js.html",
    "strip-types/src/reducer/base.js",
    "file"
  ],
  [
    "strip-types/src/store/store.js",
    "file/strip-types/src/store/store.js.html",
    "strip-types/src/store/store.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/core.js",
    "file/strip-types/src/test-framework/core.js.html",
    "strip-types/src/test-framework/core.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/factory.js",
    "file/strip-types/src/test-framework/dom-mutation/factory.js.html",
    "strip-types/src/test-framework/dom-mutation/factory.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/factory.js~dommutationfactory.get",
    "class/strip-types/src/test-framework/dom-mutation/factory.js~DOMMutationFactory.html#static-method-get",
    "strip-types/src/test-framework/dom-mutation/factory.js~DOMMutationFactory.get",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/factory.js~dommutationfactory.ismutationobserveravailable",
    "class/strip-types/src/test-framework/dom-mutation/factory.js~DOMMutationFactory.html#static-method-isMutationObserverAvailable",
    "strip-types/src/test-framework/dom-mutation/factory.js~DOMMutationFactory.isMutationObserverAvailable",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-base.js",
    "file/strip-types/src/test-framework/dom-mutation/mutation-base.js.html",
    "strip-types/src/test-framework/dom-mutation/mutation-base.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-base.js~dommutationbase#getmutationdata",
    "class/strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase.html#instance-method-getMutationData",
    "strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase#getMutationData",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-base.js~dommutationbase#isactive",
    "class/strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase.html#instance-method-isActive",
    "strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase#isActive",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-base.js~dommutationbase#observe",
    "class/strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase.html#instance-method-observe",
    "strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase#observe",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-base.js~dommutationbase#restore",
    "class/strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase.html#instance-method-restore",
    "strip-types/src/test-framework/dom-mutation/mutation-base.js~DOMMutationBase#restore",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-events.js",
    "file/strip-types/src/test-framework/dom-mutation/mutation-events.js.html",
    "strip-types/src/test-framework/dom-mutation/mutation-events.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-events.js~dommutationevents#restore",
    "class/strip-types/src/test-framework/dom-mutation/mutation-events.js~DOMMutationEvents.html#instance-method-restore",
    "strip-types/src/test-framework/dom-mutation/mutation-events.js~DOMMutationEvents#restore",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-observer.js",
    "file/strip-types/src/test-framework/dom-mutation/mutation-observer.js.html",
    "strip-types/src/test-framework/dom-mutation/mutation-observer.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/dom-mutation/mutation-observer.js~dommutationobserver#restore",
    "class/strip-types/src/test-framework/dom-mutation/mutation-observer.js~DOMMutationObserver.html#instance-method-restore",
    "strip-types/src/test-framework/dom-mutation/mutation-observer.js~DOMMutationObserver#restore",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-util.js",
    "file/strip-types/src/test-framework/dom-util.js.html",
    "strip-types/src/test-framework/dom-util.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/dom-util.js~domutil#sendclickevent",
    "class/strip-types/src/test-framework/dom-util.js~DOMUtil.html#instance-method-sendClickEvent",
    "strip-types/src/test-framework/dom-util.js~DOMUtil#sendClickEvent",
    "method"
  ],
  [
    "strip-types/src/test-framework/dom-util.js~domutil#sendresizeevent",
    "class/strip-types/src/test-framework/dom-util.js~DOMUtil.html#instance-method-sendResizeEvent",
    "strip-types/src/test-framework/dom-util.js~DOMUtil#sendResizeEvent",
    "method"
  ],
  [
    "strip-types/src/test-framework/inject.js",
    "file/strip-types/src/test-framework/inject.js.html",
    "strip-types/src/test-framework/inject.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/inject.js~inject.attach",
    "class/strip-types/src/test-framework/inject.js~Inject.html#static-method-attach",
    "strip-types/src/test-framework/inject.js~Inject.attach",
    "method"
  ],
  [
    "strip-types/src/test-framework/inject.js~inject.destroy",
    "class/strip-types/src/test-framework/inject.js~Inject.html#static-method-destroy",
    "strip-types/src/test-framework/inject.js~Inject.destroy",
    "method"
  ],
  [
    "strip-types/src/test-framework/mock.js",
    "file/strip-types/src/test-framework/mock.js.html",
    "strip-types/src/test-framework/mock.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/mock.js~mock#attach",
    "class/strip-types/src/test-framework/mock.js~Mock.html#instance-method-attach",
    "strip-types/src/test-framework/mock.js~Mock#attach",
    "method"
  ],
  [
    "strip-types/src/test-framework/mock.js~mock#constructor",
    "class/strip-types/src/test-framework/mock.js~Mock.html#instance-constructor-constructor",
    "strip-types/src/test-framework/mock.js~Mock#constructor",
    "method"
  ],
  [
    "strip-types/src/test-framework/mock.js~mock#destroy",
    "class/strip-types/src/test-framework/mock.js~Mock.html#instance-method-destroy",
    "strip-types/src/test-framework/mock.js~Mock#destroy",
    "method"
  ],
  [
    "strip-types/src/test-framework/mock.js~mock#mock",
    "class/strip-types/src/test-framework/mock.js~Mock.html#instance-get-mock",
    "strip-types/src/test-framework/mock.js~Mock#mock",
    "member"
  ],
  [
    "strip-types/src/test-framework/mock.js~mock#mock",
    "class/strip-types/src/test-framework/mock.js~Mock.html#instance-set-mock",
    "strip-types/src/test-framework/mock.js~Mock#mock",
    "member"
  ],
  [
    "strip-types/src/test-framework/modulejs.js",
    "file/strip-types/src/test-framework/modulejs.js.html",
    "strip-types/src/test-framework/modulejs.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/modulejs.js~modulejs#constructor",
    "class/strip-types/src/test-framework/modulejs.js~ModuleJS.html#instance-constructor-constructor",
    "strip-types/src/test-framework/modulejs.js~ModuleJS#constructor",
    "method"
  ],
  [
    "strip-types/src/test-framework/modulejs.js~modulejs#getmodule",
    "class/strip-types/src/test-framework/modulejs.js~ModuleJS.html#instance-method-getModule",
    "strip-types/src/test-framework/modulejs.js~ModuleJS#getModule",
    "method"
  ],
  [
    "strip-types/src/test-framework/proxy-spy-handler.js",
    "file/strip-types/src/test-framework/proxy-spy-handler.js.html",
    "strip-types/src/test-framework/proxy-spy-handler.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/proxy-spy-handler.js~proxyspyhandler#constructor",
    "class/strip-types/src/test-framework/proxy-spy-handler.js~ProxySpyHandler.html#instance-constructor-constructor",
    "strip-types/src/test-framework/proxy-spy-handler.js~ProxySpyHandler#constructor",
    "method"
  ],
  [
    "strip-types/src/test-framework/proxy-spy-handler.js~proxyspyhandler#get",
    "class/strip-types/src/test-framework/proxy-spy-handler.js~ProxySpyHandler.html#instance-method-get",
    "strip-types/src/test-framework/proxy-spy-handler.js~ProxySpyHandler#get",
    "method"
  ],
  [
    "strip-types/src/test-framework/proxy-spy-handler.js~proxyspyhandler#getpropertyregister",
    "class/strip-types/src/test-framework/proxy-spy-handler.js~ProxySpyHandler.html#instance-method-getPropertyRegister",
    "strip-types/src/test-framework/proxy-spy-handler.js~ProxySpyHandler#getPropertyRegister",
    "method"
  ],
  [
    "strip-types/src/test-framework/spy.js",
    "file/strip-types/src/test-framework/spy.js.html",
    "strip-types/src/test-framework/spy.js",
    "file"
  ],
  [
    "strip-types/src/test-framework/spy.js~spy#get",
    "class/strip-types/src/test-framework/spy.js~Spy.html#instance-method-get",
    "strip-types/src/test-framework/spy.js~Spy#get",
    "method"
  ],
  [
    "strip-types/src/test-framework/spy.js~spy#intercept",
    "class/strip-types/src/test-framework/spy.js~Spy.html#instance-method-intercept",
    "strip-types/src/test-framework/spy.js~Spy#intercept",
    "method"
  ],
  [
    "strip-types/src/test-framework/spy.js~spy#mock",
    "class/strip-types/src/test-framework/spy.js~Spy.html#instance-method-mock",
    "strip-types/src/test-framework/spy.js~Spy#mock",
    "method"
  ],
  [
    "strip-types/src/test-framework/spy.js~spy#restore",
    "class/strip-types/src/test-framework/spy.js~Spy.html#instance-method-restore",
    "strip-types/src/test-framework/spy.js~Spy#restore",
    "method"
  ],
  [
    "strip-types/src/test-framework/spy.js~spy#watch",
    "class/strip-types/src/test-framework/spy.js~Spy.html#instance-method-watch",
    "strip-types/src/test-framework/spy.js~Spy#watch",
    "method"
  ],
  [
    "strip-types/src/test-framework/spy.js~spy#watched",
    "class/strip-types/src/test-framework/spy.js~Spy.html#instance-method-watched",
    "strip-types/src/test-framework/spy.js~Spy#watched",
    "method"
  ],
  [
    "strip-types/test/bootstrap.js",
    "file/strip-types/test/bootstrap.js.html",
    "strip-types/test/bootstrap.js",
    "file"
  ],
  [
    "strip-types/test/javascript/component/base/test.base-controller.js",
    "file/strip-types/test/javascript/component/base/test.base-controller.js.html",
    "strip-types/test/javascript/component/base/test.base-controller.js",
    "file"
  ],
  [
    "strip-types/test/javascript/component/base/test.base-view.js",
    "file/strip-types/test/javascript/component/base/test.base-view.js.html",
    "strip-types/test/javascript/component/base/test.base-view.js",
    "file"
  ],
  [
    "strip-types/test/javascript/component/base/test.event-actions.js",
    "file/strip-types/test/javascript/component/base/test.event-actions.js.html",
    "strip-types/test/javascript/component/base/test.event-actions.js",
    "file"
  ],
  [
    "strip-types/test/javascript/polyfill/test.polyfill.js",
    "file/strip-types/test/javascript/polyfill/test.polyfill.js.html",
    "strip-types/test/javascript/polyfill/test.polyfill.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test-framework/test.dom-observer.js",
    "file/strip-types/test/javascript/test-framework/test.dom-observer.js.html",
    "strip-types/test/javascript/test-framework/test.dom-observer.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test-framework/test.mock.js",
    "file/strip-types/test/javascript/test-framework/test.mock.js.html",
    "strip-types/test/javascript/test-framework/test.mock.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test-framework/test.modulejs.js",
    "file/strip-types/test/javascript/test-framework/test.modulejs.js.html",
    "strip-types/test/javascript/test-framework/test.modulejs.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test-framework/test.spy.js",
    "file/strip-types/test/javascript/test-framework/test.spy.js.html",
    "strip-types/test/javascript/test-framework/test.spy.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test.clone-object.js",
    "file/strip-types/test/javascript/test.clone-object.js.html",
    "strip-types/test/javascript/test.clone-object.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test.cookie-storage.js",
    "file/strip-types/test/javascript/test.cookie-storage.js.html",
    "strip-types/test/javascript/test.cookie-storage.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test.emit-core-ready-event.js",
    "file/strip-types/test/javascript/test.emit-core-ready-event.js.html",
    "strip-types/test/javascript/test.emit-core-ready-event.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test.environment.js",
    "file/strip-types/test/javascript/test.environment.js.html",
    "strip-types/test/javascript/test.environment.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test.erb-templating.js",
    "file/strip-types/test/javascript/test.erb-templating.js.html",
    "strip-types/test/javascript/test.erb-templating.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test.event-bus.js",
    "file/strip-types/test/javascript/test.event-bus.js.html",
    "strip-types/test/javascript/test.event-bus.js",
    "file"
  ],
  [
    "strip-types/test/javascript/test.logger.js",
    "file/strip-types/test/javascript/test.logger.js.html",
    "strip-types/test/javascript/test.logger.js",
    "file"
  ],
  [
    "test/bootstrap.js",
    "test-file/test/bootstrap.js.html",
    "test/bootstrap.js",
    "testFile"
  ],
  [
    "test/javascript/component/base/test.base-controller.js",
    "test-file/test/javascript/component/base/test.base-controller.js.html",
    "test/javascript/component/base/test.base-controller.js",
    "testFile"
  ],
  [
    "test/javascript/component/base/test.base-view.js",
    "test-file/test/javascript/component/base/test.base-view.js.html",
    "test/javascript/component/base/test.base-view.js",
    "testFile"
  ],
  [
    "test/javascript/component/base/test.event-actions.js",
    "test-file/test/javascript/component/base/test.event-actions.js.html",
    "test/javascript/component/base/test.event-actions.js",
    "testFile"
  ],
  [
    "test/javascript/polyfill/test.polyfill.js",
    "test-file/test/javascript/polyfill/test.polyfill.js.html",
    "test/javascript/polyfill/test.polyfill.js",
    "testFile"
  ],
  [
    "test/javascript/test-framework/test.dom-observer.js",
    "test-file/test/javascript/test-framework/test.dom-observer.js.html",
    "test/javascript/test-framework/test.dom-observer.js",
    "testFile"
  ],
  [
    "test/javascript/test-framework/test.mock.js",
    "test-file/test/javascript/test-framework/test.mock.js.html",
    "test/javascript/test-framework/test.mock.js",
    "testFile"
  ],
  [
    "test/javascript/test-framework/test.modulejs.js",
    "test-file/test/javascript/test-framework/test.modulejs.js.html",
    "test/javascript/test-framework/test.modulejs.js",
    "testFile"
  ],
  [
    "test/javascript/test-framework/test.spy.js",
    "test-file/test/javascript/test-framework/test.spy.js.html",
    "test/javascript/test-framework/test.spy.js",
    "testFile"
  ],
  [
    "test/javascript/test.clone-object.js",
    "test-file/test/javascript/test.clone-object.js.html",
    "test/javascript/test.clone-object.js",
    "testFile"
  ],
  [
    "test/javascript/test.cookie-storage.js",
    "test-file/test/javascript/test.cookie-storage.js.html",
    "test/javascript/test.cookie-storage.js",
    "testFile"
  ],
  [
    "test/javascript/test.emit-core-ready-event.js",
    "test-file/test/javascript/test.emit-core-ready-event.js.html",
    "test/javascript/test.emit-core-ready-event.js",
    "testFile"
  ],
  [
    "test/javascript/test.environment.js",
    "test-file/test/javascript/test.environment.js.html",
    "test/javascript/test.environment.js",
    "testFile"
  ],
  [
    "test/javascript/test.erb-templating.js",
    "test-file/test/javascript/test.erb-templating.js.html",
    "test/javascript/test.erb-templating.js",
    "testFile"
  ],
  [
    "test/javascript/test.event-bus.js",
    "test-file/test/javascript/test.event-bus.js.html",
    "test/javascript/test.event-bus.js",
    "testFile"
  ],
  [
    "test/javascript/test.logger.js",
    "test-file/test/javascript/test.logger.js.html",
    "test/javascript/test.logger.js",
    "testFile"
  ]
]